name: Build and Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: ['24.x'] # LTS versions

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java (Temurin 25)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
          cache: maven

      - name: Install PNPM
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build and publish Electron app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm run publish:all # publish all profiles (node + spring)
permissions:
  packages: write
  contents: write
